### ISSUE TITLE
Move command line parser to UI

### ISSUE THREAD

**Issue by mpostol** [mpostol/UA-ModelCompiler#33]
- [x] move parser
- [x] add UT

**Comment by mpostol** [comment]
```TXT
C:\VS.git\UAOOI\OPCF\mpostol.UA-ModelCompiler>BuildStandardTypes.bat >bst.log
Could not load resource 'ModelCompiler.Design.v104.BuiltInTypes.xml'.
   at Opc.Ua.Schema.SchemaValidator.LoadResource(Type type, String path, Assembly assembly)
   at OOI.ModelCompiler.ModelCompilerValidator.Validate2(IList`1 designFilePaths, String identifierFilePath, Boolean generateIds)
   at OOI.ModelCompiler.ModelGenerator2.ValidateAndUpdateIds(IList`1 designFilePaths, String identifierFilePath, UInt32 startId, String specificationVersion, Boolean useAllowSubtypes)
   at OOI.ModelCompiler.ModelCompilerAPI.Execute()
   at OOI.ModelCompilerUI.EntryPoint.ProcessCommandLine(String commandLine, Boolean noGui, IGUIHandling guiHandling) in C:\VS.git\UAOOI\OPCF\mpostol.UA-ModelCompiler\ModelCompilerUI\EntryPoint.cs:line 96
```

**Comment by mpostol** [comment]
Opc.Ua.Attributes.cs is generated but different that the origin
